name: Backport to solana-v2.0

on:
  push:
    branches: [main]

jobs:
  backport:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        
      - name: Backport to v2.0
        uses: ./.github/actions/backport
        with:
          label: v2.0
          base_branch: solana-v2.0
          github_token: ${{ secrets.GITHUB_TOKEN }}
